# 로컬 환경
spring:
  config:
    import: workflow.yml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/saessagdb
    username: root
    password: '0000'
  jpa:
    hibernate:
      ddl-auto: update
