# 로컬 환경
spring:
  profiles:
    active: local  # 기본 프로파일 설정
  config:
    import: workflow.yml
  datasource:
    url: ${local_db_url}
    username: ${local_db_username}
    password: ${local_db_password}
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME} # 실제 Gmail 주소
    password: ${MAIL_APP_PASSWORD} # Gmail 앱 비밀번호
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true